dist: trusty

language: node_js
cache:
  directories:
    - node_modules

node_js:
  - "8.11.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq

install:
  - npm i
  - truffle version

script:
  - npm run ganache 2> /dev/null 1> /dev/null &
  - sleep 5 # to make sure ganache-cli is up and running before compiling
  - rm -rf build
  - npm run lint
  - npm run test
  - kill -9 $(lsof -t -i:8545)
