dist: trusty

language: node_js
cache:
  directories:
    - node_modules

node_js:
  - "8.11.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq

install:
  - npm install -g ganache-cli truffle
  - npm i
  - rm -rf build/ # remove any remaining artifacts from a previous build
  - truffle version

script:
  - ganache-cli --gasLimit 6721975 2> /dev/null 1> /dev/null &
  - sleep 5 # to make sure ganache-cli is up and running before compiling
  - rm -rf build
  - truffle compile
  - truffle migrate --reset --network development
  - truffle test
  - npm run solium
  - npm run lint
  - kill -9 $(lsof -t -i:8545)
