site_name: DAOstack Access Control Docs
repo_url: https://github.com/daostack/access_control/
repo_name: daostack/access_control
site_description: An access control mechanism for DAOstack.
docs_dir: docs
extra_templates:
- index.html
markdown_extensions:
- admonition
- codehilite:
    linenums: true
- toc:
    permalink: true
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'amber'
extra:
  social:
  - type: 'github'
    link: 'https://github.com/daostack/access_control'
  - type: 'slack'
    link: 'https://daostack.slack.com'
  - type: 'telegram'
    link: 'https://t.me/daostackcommunity'

pages:
- Home: README.md
- Generated Docs:
  - Permissioned: generated_docs/Permissioned.md
  - ERC1480: generated_docs/ERC1480.md
  - ERC1480Interface: generated_docs/ERC1480Interface.md
  - ERC1480Storage: generated_docs/ERC1480Storage.md
  - Group: generated_docs/Group.md
  - IntersectionGroup: generated_docs/IntersectionGroup.md
  - InverseGroup: generated_docs/InverseGroup.md
  - UnionGroup: generated_docs/UnionGroup.md
  - Examples:
    - Company Example: generated_docs/examples/Company.md